apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-rocket
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: hello-rocket
        image: demo-rust:1.0.0
---
apiVersion: v1
kind: Service
metadata:
  name: hello-rocket-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    bb: web
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30001